Repository zainfathoni/kelas.rumahberbagi.com, pull requests merged in 2021-12, with the labels that each got.

#2 Add GitHub Actions badge and Logout spec
  .kodiak.toml
  README.md
  app/services/email.server.tsx
  e2e/logout.spec.ts
Labels: automerge

#3 ci: Update seed data
  app/components/header.tsx
  app/components/hero-section.tsx
  e2e/auth.json
  package.json
  prisma/seed.ts
  prisma/test.db
Labels: automerge

#4 ci: use playwright-testing-library to query form fields accessibly
  app/components/form-elements.tsx
  e2e/base-test.ts
  e2e/dashboard.spec.ts
  e2e/login.spec.ts
  package-lock.json
  package.json
Labels: automerge

#5 test: Magic link
  e2e/magic.json
  e2e/magic.spec.ts
Labels: automerge

#6 ci: setup Git pre-commit hooks & GitHub Actions caching
  .github/workflows/test.yml
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc.json
  app/components/form-elements.tsx
  commitlint.config.js
  e2e/base-test.ts
  e2e/magic.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
Labels: automerge

#7 ci: improve developer experience
  .env.example
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  .github/workflows/test.yml
  .gitignore
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
  README.md
  app/components/badge.tsx
  app/components/footer.tsx
  app/components/form-elements.tsx
  app/components/header.tsx
  app/components/hero-section.tsx
  app/components/logo.tsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/routes/dashboard.tsx
  app/routes/index.tsx
  app/routes/login.tsx
  app/routes/logout.tsx
  app/routes/magic.tsx
  app/services/auth.server.ts
  app/services/email-provider.server.ts
  app/services/email.server.tsx
  app/services/session.server.ts
  app/services/verifier.server.ts
  app/utils/db.server.ts
  app/utils/misc.ts
  app/utils/validators.ts
  commitlint.config.js
  e2e/auth.json
  e2e/dashboard.spec.ts
  e2e/login.spec.ts
  e2e/logout.spec.ts
  e2e/magic.spec.ts
  mocks/handlers.ts
  package-lock.json
  package.json
  playwright.config.ts
  prisma/seed.ts
  tsconfig.json
Labels: automerge

#8 test: improve e2e tests infrastructure
  .env.example
  .github/pull_request_template.md
  app/utils/misc.ts
  e2e/auth.json
  e2e/base-test.ts
  e2e/logout.spec.ts
  playwright.config.ts
Labels: automerge

#9 test: configure baseURL
  e2e/dashboard.spec.ts
  e2e/login.spec.ts
  e2e/logout.spec.ts
  playwright.config.ts
Labels: automerge

#11 docs: complete pre-launch checklist
  .markdownlintignore
  CODE_OF_CONDUCT.md
  LICENSE
Labels: documentation, automerge, dx

#12 docs: add more badges to the README.md file
  README.md
Labels: automerge

#14 docs: update Epic issue template
  .github/ISSUE_TEMPLATE/epic.md
Labels: documentation, automerge

#16 docs: update Feature Request issue template
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/test.yml
  .markdownlint.json
  .prettierrc.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
  README.md
Labels: documentation, automerge

#23 docs: add important links
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
  README.md
Labels: documentation, automerge

#24 ci: setup CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: automerge, ci-cd, security

#26 docs: add first-time contributors link
  README.md
Labels: documentation, automerge

#27 docs: add project description
  README.md
  docs/index.md
  docs/values.md
Labels: documentation, automerge

#28 docs: document use cases
  docs/diagrams/payment-flow.puml
  docs/diagrams/use-cases.puml
  docs/index.md
  docs/use-cases.md
Labels: documentation, automerge

#29 docs: render PlantUML diagrams in use-cases.md
  docs/diagrams/use-cases.puml
  docs/use-cases.md
Labels: documentation, automerge

#30 docs: add Entity Relationship Diagram
  README.md
  docs/diagrams.md
  docs/diagrams/erd.puml
  docs/diagrams/transaction-flow.puml
  docs/index.md
  docs/use-cases.md
Labels: documentation, automerge

#32 docs: update Use Case Diagram
  docs/diagrams/use-cases.puml
Labels: documentation, automerge

#44 docs: update issue templates
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .markdownlint.json
Labels: documentation, automerge

#46 docs: add state diagrams
  docs/diagrams.md
  docs/diagrams/subscription-state.puml
  docs/diagrams/transaction-state.puml
Labels: documentation, automerge

#48 docs: change state diagrams direction from left to right
  docs/diagrams/subscription-state.puml
  docs/diagrams/transaction-state.puml
Labels: documentation, automerge

#51 ci: add .clabot file
  .clabot
Labels: automerge, dx

#53 fix: add pre-script for install deps playwright
  package.json
Labels: automerge, dx

#55 ci: configure bots
  .all-contributorsrc
  .kodiak.toml
Labels: automerge, ci-cd

#57 docs: update Transaction Flow diagram with new copies
  docs/diagrams/transaction-flow.puml
Labels: documentation, automerge

#59 ci: automatically approve zainfathoni's PRs due to no other approvers
  .kodiak.toml
Labels: automerge, ci-cd

#58 docs: simplify copy between frontend and backend
  docs/diagrams/transaction-flow.puml
Labels: documentation, automerge

#61 build: update package-lock.json file
  package-lock.json
  package.json
Labels: automerge, dependencies

#62 build: require node@16 & npm@8 to avoid `package-lock.json` mismatches
  .github/workflows/test.yml
  README.md
  package.json
Labels: automerge, ci-cd, dx

#34 style: trying to add benefit section component and other components to index page
  app/components/benefit-section.tsx
  app/components/cta-section.tsx
  app/components/icons/chalkboard-teacher.tsx
  app/components/icons/comments-alt.tsx
  app/components/icons/file-invoice.tsx
  app/components/icons/file-signature.tsx
  app/components/icons/file-video.tsx
  app/components/icons/whatsapp.tsx
  app/components/qna-section.tsx
  app/components/sections/content.tsx
  app/components/sections/pricing.tsx
  app/fonts.css
  app/root.tsx
  app/routes/index.tsx
  package-lock.json
  package.json
  public/images/foto-vika.jpeg
  public/images/interaction-preview.jpeg
  public/images/planner-preview.jpeg
  tailwind.config.js
Labels: automerge

#60 feat: cta to purchase the course
  app/routes/dashboard.tsx
  app/routes/dashboard/index.tsx
  app/routes/dashboard/purchase.tsx
  app/routes/dashboard/settings.tsx
  e2e/cta.spec.ts
  e2e/dashboard.spec.ts
  e2e/settings.spec.ts
Labels: automerge

#45 feat: add transaction entity to store payment information
  app/models/enum.ts
  prisma/migrations/20211225043237_add_transaction_table/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: automerge

#66 feat: purchase route
  app/models/subscription.ts
  app/routes/dashboard/index.tsx
  app/routes/dashboard/purchase.tsx
  app/routes/dashboard/purchase/index.tsx
  e2e/cta.spec.ts
Labels: automerge

#76 ci: upgrade lockfileVersion to 2
  package-lock.json
Labels: automerge

#74 ci: annotate docs links
  .kodiak.toml
Labels: automerge

#77 docs: update feature-request issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation, automerge

#73 docs: explain GitHub Project views
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
Labels: automerge

#81 feat: implement a new Dashboard layout
  app/routes/dashboard.tsx
  app/routes/dashboard/profile.tsx
  app/routes/dashboard/profile/edit.tsx
  app/routes/dashboard/profile/index.tsx
  e2e/profile.spec.ts
Labels: automerge

#82 refactor: replace anchor with Links and fix flaky tests
  app/components/cta-section.tsx
  app/components/sections/pricing.tsx
  app/routes/dashboard.tsx
  app/routes/dashboard/profile/index.tsx
  e2e/profile.spec.ts
  prisma/test.db
Labels: automerge, testing, ux

#85 docs: rename View Member Detail to View Transaction Details
  docs/diagrams/transaction-flow.puml
Labels: documentation, automerge

#86 docs: add consumption table in the ERD
  app/models/enum.ts
  docs/diagrams.md
  docs/diagrams/consumption-state.puml
  docs/diagrams/erd.puml
Labels: documentation, automerge

#87 docs: add Routes Table to visualise all possible routes
  app/models/enum.ts
  docs/diagrams.md
  docs/diagrams/routes-table.puml
  docs/diagrams/transaction-state.puml
Labels: documentation, automerge

#88 docs: add course slug and content slug fields
  docs/diagrams/erd.puml
Labels: documentation, automerge

#89 fix: flaky e2e test in noscript browser
  e2e/logout.spec.ts
Labels: automerge, dx, testing

#90 docs: add a datetime field in the Transaction table
  docs/diagrams/erd.puml
Labels: documentation, automerge

#91 docs: update Transaction relationship
  docs/diagrams/erd.puml
Labels: documentation, automerge

#93 docs: denormalize Subcription table by adding authorId field
  docs/diagrams/erd.puml
Labels: documentation, automerge

#96 docs: remove unnecessary subscriptions route
  docs/diagrams/routes-table.puml
Labels: documentation, automerge
