Repository zainfathoni/kelas.rumahberbagi.com, pull requests merged in 2022-01, with the labels that each got.

#78 style: styling profile route according to tailwind ui multi-column di…
  app/routes/dashboard.tsx
  app/routes/dashboard/profile/index.tsx
  e2e/profile.spec.ts
  prisma/test.db
Labels: automerge

#97 feat: add Transaction Details Page
  app/models/transaction.ts
  app/routes/dashboard/transactions.tsx
  app/routes/dashboard/transactions/$transactionId.tsx
  app/routes/dashboard/transactions/index.tsx
  app/utils/assertions.ts
  app/utils/locales.ts
  e2e/transaction-details.spec.ts
  prisma/seed.ts
  prisma/test.db
Labels: automerge

#100 ci: configure Jest for Unit & Integration Testing
  .eslintrc.json
  .github/workflows/test.yml
  .gitignore
  app/components/__tests__/footer.test.tsx
  app/components/footer.tsx
  app/root.tsx
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  test/jest-common.js
  test/jest.client.js
  test/jest.server.js
Labels: automerge

#106 ci: configure ESLint for YAML files and fix React import requirements
  .eslintrc.json
  app/components/__tests__/footer.test.tsx
  app/components/footer.tsx
  babel.config.js
  package.json
  test/jest.client.js
Labels: automerge, ci-cd, scripting, testing

#107 refactor: update Transaction, Subscription, and Course tables
  e2e/auth.json
  e2e/transaction-details.spec.ts
  prisma/migrations/20220106174645_update_transaction_subcription_course/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  prisma/test.db
Labels: automerge

#108 refactor: update e2e test fixtures automatically
  .gitignore
  app/models/__mocks__/course.ts
  app/models/__mocks__/transaction.ts
  app/models/__mocks__/user.ts
  app/models/enum.ts
  app/services/__tests__/email.server.test.ts
  app/services/email-provider.server.ts
  app/services/email.server.tsx
  app/utils/fixtures.ts
  babel.config.js
  e2e/auth.json
  e2e/cta.spec.ts
  e2e/fixtures/transactions/.gitkeep
  e2e/fixtures/users/.gitkeep
  e2e/login.spec.ts
  e2e/logout.spec.ts
  e2e/magic.json
  e2e/magic.spec.ts
  e2e/profile.spec.ts
  e2e/transaction-details.spec.ts
  jest.config.js
  package-lock.json
  package.json
  playwright-global-setup.ts
  playwright.config.ts
  prisma/seed.ts
  prisma/test.db
  test/jest.server.js
Labels: automerge

#110 feat: add Transaction datetime
  .gitignore
  app/models/__mocks__/transaction.ts
  prisma/migrations/20220108151732_add_transaction_datetime/migration.sql
  prisma/schema.prisma
Labels: automerge, scripting

#111 fix: handle authentication error
  app/root.tsx
  e2e/auth-error.spec.ts
  e2e/fixtures/auth-error.json
Labels: bug, automerge, ux
